# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  resources:
    - resource: DeveloperMode
      directives:
        description: Enable Developer Mode
        module: Microsoft.Windows.Developer
        allowPrerelease: true
      settings:
        Ensure: Present

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install PowerShell 7
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        id: Git.Git
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install GitHub CLI
        allowPrerelease: true
      settings:
        id: GitHub.cli
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Docker Desktop
        allowPrerelease: true
      settings:
        id: Docker.DockerDesktop
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install AWS CLI
        allowPrerelease: true
      settings:
        id: Amazon.AWSVPNClient
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Office
        allowPrerelease: true
      settings:
        id: Microsoft.Office
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Teams
        allowPrerelease: true
      settings:
        id: Microsoft.Teams
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Ubuntu 22.04 (WSL)
        allowPrerelease: true
      settings:
        id: Canonical.Ubuntu.2204
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Mirantis Lens
        allowPrerelease: true
      settings:
        id: Mirantis.Lens
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install PowerToys
      settings:
        id: Microsoft.PowerToys
        source: winget

    # - resource: Microsoft.WinGet.DSC/WinGetPackage
    #   directives:
    #     description: Install Windows Terminal
    #     allowPrerelease: true
    #   settings:
    #     id: Microsoft.Windows.Terminal
    #     source: winget

    # - resource: Microsoft.WinGet.DSC/WinGetPackage
    #   directives:
    #     description: Install 7zip
    #     allowPrerelease: true
    #   settings:
    #     id: 7zip.7zip
    #     source: winget

    - resource: PSDscResources/Registry
      directives:
        description: Show Hidden Files
      settings:
        Key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        ValueName: Hidden
        ValueType: DWord
        ValueData: 1

    - resource: PSDscResources/Registry
      directives:
        description: Do not Hide File Extensions
      settings:
        Key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        ValueName: HideFileExt
        ValueType: DWord
        ValueData: 0

    - resource: PSDscResources/Registry
      directives:
        description: Navigation Pane Expand to Current Folder
      settings:
        Key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        ValueName: NavPaneExpandToCurrentFolder
        ValueType: DWord
        ValueData: 1

    - resource: PSDscResources/Registry
      directives:
        description: Turn off Search box on Taskbar
      settings:
        Key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Search
        ValueName: SearchboxTaskbarMode
        ValueType: DWord
        ValueData: 0

    - resource: DSCR_Font/cFont
      directives:
        description: Install SauceCodePro Font
      settings:
        FontName: SauceCodePro NF Regular
        FontFile: https://github.com/ryanoasis/nerd-fonts/raw/2.1.0/patched-fonts/SourceCodePro/Regular/complete/Sauce%20Code%20Pro%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf

    - resource: DSCR_Font/cFont
      directives:
        description: Install CaskaydiaCove Font
      settings:
        FontName: CaskaydiaCove NF Regular
        FontFile: https://github.com/ryanoasis/nerd-fonts/raw/2.1.0/patched-fonts/CascadiaCode/complete/Caskaydia%20Cove%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf
